version: '3'

services:
  traccar-db:
    container_name: traccar-db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: unless-stopped
    image: mariadb:10.1
    network_mode: bridge
    volumes:
      - /volume1/Media/SmartHome/Config/traccar-db:/var/lib/mysql
    environment:
      - PUID=1026
      - PGID=101
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=traccar
      - MYSQL_USER=traccar
      - /etc/localtime:/etc/localtime:ro
      - TZ=Asia/Jerusalem
    ports:
      - "3334:3306"
    labels:
      - "com.ouroboros.enable=true"

  traccar-app:
    container_name: traccar-app
    image: traccar/traccar
    restart: unless-stopped
    ports:
      - "8082:8082"
      - "5055:5055"
      - "5055:5055/udp"
    depends_on:
      - "traccar-db"
    links:
      - "traccar-db:db"
    network_mode: bridge
    volumes:
      - /volume1/Media/SmartHome/Config/traccar/logs:/opt/traccar/logs:rw
      - /volume1/Media/SmartHome/Config/traccar/conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=Asia/Jerusalem
    labels:
      - "com.ouroboros.enable=true"
