version: '3'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    labels:
      - "com.ouroboros.enable=true"
  app:
    image: nextcloud
    ports:
      - 8787:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
    depends_on:
      - "db"
    labels:
      - "com.ouroboros.enable=true"
